name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Rename JS to JSX  # Add this step
      run: |
        find src -name "*.js" -exec sh -c 'mv "$0" "${0%.js}.jsx"' {} \;
        sed -i 's/\.js"/\.jsx"/g' src/index.jsx src/App.jsx
        sed -i 's/\.js"/\.jsx"/g' src/**/*.jsx

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
    
    - name: Verify build output
      run: |
        echo "Checking dist directory contents:"
        ls -la dist
        echo "Checking index.html content:"
        cat dist/index.html
        echo "Checking main JS file:"
        find dist/assets -name 'index-*.js' -exec head -n 5 {} \;
